num_classes: 100
epochs: 100
grad_clip: 5.0
log_frequency: 100

model:
  name: ResNet18
  num_classes: 10

criterion:
  name: MadrysLoss
  epsilon: 0.03137254901
  perturb_steps: 10
  step_size: 0.00784313725

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: MultiStepLR
  milestones: [75, 90, 100]
  gamma: 0.1

dataset:
  name: DatasetGenerator
  train_batch_size: 128
  eval_batch_size: 128
